(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A2=function(a){a.S("cardstatechange",g.ZK(a)&&g.$K(a)?1:0)},nsa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.ck&&a.dataset){if(g.Rc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.md("pollChoiceIndex"))},osa=function(a){return Math.pow(a,3)},psa=function(a){return 3*a*a-2*a*a*a},B2=function(a,b){var c=g.Co("use_default_events_client")?void 0:g.Vq;
(0,g.y)(b,function(d){d={csn:a,ve:g.bs(d),eventType:4};var e={Vk:g.is(a),Yi:a};"UNDEFINED_CSN"==a?g.ws("visualElementShown",d,e):c?g.kq("visualElementShown",d,c,e):g.Wq("visualElementShown",d,e)})},C2=function(a,b){var c=g.Co("use_default_events_client")?void 0:g.Vq;
(0,g.y)(b,function(d){var e=void 0;e=void 0===e?!1:e;d={csn:a,ve:g.bs(d),eventType:e?16:8};e={Vk:g.is(a),Yi:a,vE:e};"UNDEFINED_CSN"==a?g.ws("visualElementHidden",d,e):c?g.kq("visualElementHidden",d,c,e):g.Wq("visualElementHidden",d,e)})},F2=function(a){a=g.Sa(a);
delete D2[a];g.Nb(D2)&&E2&&E2.stop()},rsa=function(){E2||(E2=new g.H(function(){qsa()},20));
var a=E2;a.isActive()||a.start()},qsa=function(){var a=(0,g.G)();
g.Ab(D2,function(b){ssa(b,a)});
g.Nb(D2)||rsa()},G2=function(a,b,c,d){g.Ln.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.G=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.F=0;this.B=null},ssa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.B);a.B=b;tsa(a,a.progress);1==a.progress?(a.o=0,F2(a),a.Fc(),a.km()):a.ab()&&a.Ht()},tsa=function(a,b){g.Pa(a.C)&&(b=a.C(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.G[c]-a.w[c])*b+a.w[c]},usa=function(a,b){g.Me.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},H2=function(a,b,c,d,e){G2.call(this,b,c,d,e);
this.element=a},I2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
H2.call(this,a,b,c,d,e)},J2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},vsa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.Sp(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},K2=function(a){return a.baseUrl||null},L2=function(a,b){return(0,g.xe)((0,g.Fc)(a,b,void 0),function(c){return!!c})},wsa=function(a,b,c){function d(Cc){var $b=Cc.hovercardButton;
if(!$b)return null;$b=$b.subscribeButtonRenderer;if(!$b)return null;var Jc=f($b.unsubscribedButtonText),Hg=f($b.subscribedButtonText);if($b.subscribed){var Gg=f($b.subscriberCountWithUnsubscribeText);var gn=f($b.subscriberCountText)}else Gg=f($b.subscriberCountText),gn=f($b.subscriberCountWithSubscribeText);var fj=null;return Cc.signinEndpoint&&(fj=g.Ib(Cc,"signinEndpoint","webNavigationEndpointData","url"),!fj)?null:Jc&&(Hg||fj)?{subscribed:$b.subscribed,subscribeText:Jc,subscribeCount:Gg,unsubscribeText:Hg,
unsubscribeCount:gn,enabled:$b.enabled,signinUrl:fj,classic:Cc.useClassicSubscribeButton}:null}
function e(Cc){if(Cc){var $b=[],Jc=Cc.videoId;Jc&&$b.push("v="+Jc);(Jc=Cc.playlistId)&&$b.push("list="+Jc);(Cc=Cc.startTimeSeconds)&&$b.push("t="+Cc);return"/watch?"+$b.join("&")}}
function f(Cc){if(!Cc)return null;var $b=Cc.simpleText;return $b?$b:Cc.runs?(0,g.Fc)(Cc.runs,function(Jc){return Jc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=null,t=null,u=null,z=null,C=!1,D=null,E=null,F=null,J=null,ha=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Ib(l,"browseEndpoint","browseId"))z=C,m="/channel/"+z;n=!1;p="new";(C=!!b.isSubscribe)?D=d(b):E=f(b.subscribersText)}else"WEBSITE"==
k?((F=g.Ib(l,"urlEndpoint","url"))&&(m=F),n=!0,p="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(J=f(b.productPrice)),b.additionalFeesText&&(ha=f(b.additionalFeesText)),(n=g.Ib(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.Ib(b,"title","accessibility","accessibilityData","label");var pa=b.endpoint?b.endpoint.clickTrackingParams:null,uc="";if(b.metadata){var $d=f(b.metadata);$d&&(uc=$d)}return{id:"element-"+c,type:k,title:f(b.title),metadata:uc,callToAction:f(b.callToAction),
zw:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:D,subscribersText:E,isSubscribe:C,targetUrl:m,VF:n,Ob:{itct:pa},HO:p,Mk:a?a:null,ZF:b.isPlaceholder,impressionUrls:L2(b.impressionUrls||[],K2),NF:L2(b.hovercardShowUrls||[],K2),clickUrls:L2(l.loggingUrls||[],K2),visualElement:g.$r(b.trackingParams),productPrice:J,
additionalFeesText:ha}},M2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=L2(a.impressionUrls||[],K2);a.trackingParams&&(c.visualElement=g.$r(a.trackingParams));c.elements=L2(a.elements||[],function(d,e){return wsa(b,d,e)});
return c},N2=function(a){g.wL.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.I=[];a=a.M();this.P=g.Ry(a)||g.Ty(a);this.L=!0;this.G=0;this.B=new g.O(this);g.B(this,this.B);this.B.K(this.player,g.nC("creatorendscreen"),this.MG);this.B.K(this.player,"crx_creatorendscreen",this.NG);this.B.K(this.player,"resize",this.Dy);this.B.K(window,"focus",this.EN);this.load();var b=g.re("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Je(this,function(){g.we(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},xsa=function(a){return a.player.getVideoData().lc?"current":a.P?"new":"current"},O2=function(a){return"creator-endscreen-editor"===a.player.M().playerStyle},P2=function(a,b,c){c=void 0===c?!0:c;
g.sQ(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&ysa(a);c=[];d=new g.kC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.M().o||(a.w=new g.Q({D:"div",H:"ytp-ce-shadow"}),g.jL(a.player,a.w.element,4),a.C=new g.SL(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=zsa(a,e);a.o[e.id]=f;a.F[e.id]=e;g.jL(a.player,f.element,4);var k=new g.kC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Asa(a,f,e)}g.fL(a.player,c);
a.Dy()}},ysa=function(a){var b=g.fs(),c=g.hs();
c&&b&&a.u.visualElement&&g.Cs(c,b,a.u.visualElement)},zsa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",Y:["ytp-ce-element","ytp-ce-video"],O:{tabindex:"0","aria-label":b.Mk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-covering-image",O:Q2(b)},{D:"div",H:"ytp-ce-covering-shadow-top"},{D:"a",H:"ytp-ce-covering-overlay",O:{href:R2(a,b.targetUrl),tabindex:"-1"},J:[{D:"div",Y:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Rn(b.title||"")},W:b.title},{D:"div",H:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.Q(c);break;case "PLAYLIST":c={D:"div",Y:["ytp-ce-element","ytp-ce-playlist"],O:{tabindex:"0","aria-label":b.Mk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-covering-image",O:Q2(b)},{D:"div",H:"ytp-ce-covering-shadow-top"},{D:"a",H:"ytp-ce-covering-overlay",O:{href:R2(a,b.targetUrl),tabindex:"-1"},J:[{D:"div",Y:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Rn(b.title||"")},W:b.title},{D:"div",H:"ytp-ce-playlist-count",J:[{D:"div",
H:"ytp-ce-playlist-icon"},{D:"div",H:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.Q(c);break;case "CHANNEL":c={D:"div",Y:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],O:{tabindex:"0","aria-label":b.Mk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-expanding-overlay",J:[{D:"div",H:"ytp-ce-expanding-overlay-hider"},{D:"div",H:"ytp-ce-expanding-overlay-background"},{D:"div",H:"ytp-ce-expanding-overlay-content",
J:[{D:"div",H:"ytp-ce-expanding-overlay-body",J:[{D:"div",H:"ytp-ce-expanding-overlay-body-padding",J:[{D:"a",Y:["ytp-ce-channel-title","ytp-ce-link"],O:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Rn(b.title||"")},W:b.title},b.subscribeButton?{D:"div",H:"ytp-ce-subscribe-container",J:[{D:"div",H:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",H:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",Y:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",H:"ytp-ce-expanding-image",O:Q2(b)}]};c=new g.Q(c);var d=g.de(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.M().o){var e=null;var f=b.Ob.itct}else e="endscreen",f=null;e=new g.LP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={D:"div",Y:["ytp-ce-element","ytp-ce-website"],O:{tabindex:"0","aria-label":b.Mk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-expanding-overlay",J:[{D:"div",H:"ytp-ce-expanding-overlay-hider"},{D:"div",H:"ytp-ce-expanding-overlay-background"},{D:"div",H:"ytp-ce-expanding-overlay-content",J:[{D:"div",H:"ytp-ce-expanding-overlay-body",
J:[{D:"div",H:"ytp-ce-expanding-overlay-body-padding",J:[{D:"div",H:"ytp-ce-website-title",O:{dir:g.Rn(b.title||"")},W:b.title},{D:"div",H:"ytp-ce-website-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-website-goto","ytp-ce-link"],O:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",H:"ytp-ce-expanding-image",O:Q2(b)},{D:"div",H:"ytp-ce-expanding-icon",O:Bsa(b.iconUrl)}]};c=new g.Q(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",H:"ytp-ce-merchandise-price-container",
J:[{D:"div",H:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.J.push({D:"div",H:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",Y:["ytp-ce-element","ytp-ce-merchandise"],O:{tabindex:"0","aria-label":b.Mk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-expanding-overlay",J:[{D:"div",H:"ytp-ce-expanding-overlay-hider"},{D:"div",H:"ytp-ce-expanding-overlay-background"},{D:"div",H:"ytp-ce-expanding-overlay-content",J:[{D:"div",
H:"ytp-ce-expanding-overlay-body",J:[{D:"div",H:"ytp-ce-expanding-overlay-body-padding",J:[{D:"div",H:"ytp-ce-merchandise-title",O:{dir:g.Rn(b.title||"")},W:b.title},c,{D:"div",H:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-merchandise-goto","ytp-ce-link"],O:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",H:"ytp-ce-expanding-image",O:Q2(b)},{D:"div",H:"ytp-ce-merchandise-invideo-cta-container",J:[{D:"div",H:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.Q(c)}b.ZF&&g.I(c.element,"ytp-ce-placeholder");return c},Q2=function(a){if(a.zw)var b=a.zw.thumbnails;
return Bsa(b?b[b.length-1].url:null)},Bsa=function(a){return a?{style:"background-image: url("+a+")"}:{}},Asa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ia("mouseenter",(0,g.x)(a.Ns,a,b,c));b.ia("mouseleave",(0,g.x)(a.Mt,a,b,c));a.player.M().o||b.ia("click",(0,g.x)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.ia("click",(0,g.x)(a.hA,a,c));b.ia("keypress",(0,g.x)(a.hA,a,c));b.ia("focus",(0,g.x)(function(l,m){this.Ns(l,m)},a,b,c));
b.ia("blur",(0,g.x)(function(l,m){this.Mt(l,m)},a,b,c));
b.ia("touchstart",(0,g.x)(a.Ns,a,b,c));var f=g.fe("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Jn(b.element,"ytp-ce-element-hover");g.Jn(b.element,"ytp-ce-force-expand")});
b.ia("keydown",(0,g.x)(function(l,m){this.L=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.I(l.element,"ytp-ce-force-expand"),S2(this,m.id,!0)):(g.Jn(l.element,"ytp-ce-force-expand"),g.Jn(l.element,"ytp-ce-element-hover"),S2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ia("blur",g.Ta(function(){"none"!=m.style.display&&a.L&&m.focus()})),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
c(g.fe("ytp-sb-subscribe",b.element));c(g.fe("ytp-sb-unsubscribe",b.element));b.ia("focus",d);b.ia("blur",e)},R2=function(a,b){var c=a.player.M();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.tz(c)+b}else return"";return b},S2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.K(a.o[d].element,"ytp-ce-element-shadow-show",c)},T2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||O2(a))c&&c();else{b=Csa(a,b);var e=0,f=!1,k=new g.H(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.hr(b[a],d)}},U2=function(a,b,c){T2(a,b.clickUrls,c);
(a=g.hs())&&b.VF&&g.Ds(a,b.visualElement)},Csa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Dsa(b[e],c));return d},Dsa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Esa=function(a){return g.Na(a)&&a.length?a[0]:a},V2=function(a){return"string"===typeof a?a:""},W2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Gsa=function(a){var b=Fsa;
if(null==a)return null;if(g.Oa(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Hsa=function(a){this.externalId=a},Isa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},X2=function(a){if(!a)return null;
var b=g.yc(V2(a.value));b=g.wc(b);if(!b)return null;var c=W2(a.target,Jsa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Isa(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Y2=function(a){return a.value?a.value:null},Ksa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Fsa=function(a){if(!a)return null;
var b=W2(a.type,Lsa),c=W2(a.trigger,Msa),d=Esa(a.url);d=X2(d?d:null);a=Esa(a.subscribeData);var e=a?a:null;e?(a=V2(e.external_user_id),e=V2(e.subscription_token),a=a&&e?new Hsa(a):null):a=null;return b?new Ksa(b,c,d,a):null},Z2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Nsa=function(a,b){return g.$a(a.o,b,void 0)},Osa=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Psa=function(a,b){this.merchant=a;
this.price=b},Qsa=function(a){this.o=a},Rsa=function(a,b,c){b&&(c?$2(a,(0,g.Fc)(b,g.Ta(function(d,e){return g.en(e,d)},c))):$2(a,b))},$2=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.hr(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Ssa=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.A=c;this.videoData=d;this.logger=e;this.N=f;this.u=k},a3=function(a,b){this.o=a;
this.w=b},Vsa=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Tsa(b,k))},a);
var d={D:"ul",O:{role:"radiogroup"},J:c},e={};b.bj&&(e["aria-label"]=g.IM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",H:"iv-card-content",J:[b3("h2",e,b.title),{D:"form",J:[{D:"fieldset",J:[d]}]}]}];b.bj&&(f.push("iv-card-unavailable"),d.push({D:"div",Y:["iv-card-sign-in"],J:[{D:"h2",W:"Want to vote?"},{D:"a",Y:["iv-card-sign-in-button","iv-button"],O:{href:Y2(b.bj)},J:[{D:"span",Y:["iv-button-content"],W:"Sign in"}]}]}));f=new g.Q({D:"div",
Y:f,J:d});d=f.element;Usa(b,d);vsa(a.o.o,d,g.Ta(a.A,b),a);(0,g.y)(g.ee("iv-card-poll-choice-input",d),function(k){this.o.o.ia(k,"focus",g.Ta(this.u,!0));this.o.o.ia(k,"blur",g.Ta(this.u,!1))},a);
b.bj&&(d=g.fe("iv-card-sign-in-button",d),a.w(d,b.bj,b.id,b.Ob,b.Gc.click,5));return f},Wsa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.aP?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.YF&&b.Uv?{D:"span",Y:d,O:e,W:b.Uv}:"";c={D:"div",Y:["iv-card",c],J:[{D:"a",H:"iv-click-target",O:{href:Y2(b.url)},J:[c3(b.gj,d?{D:"div",H:"iv-card-image-text",J:[d,b.priceText]}:""),{D:"div",H:"iv-card-content",J:[{D:"h2",H:"iv-card-primary-link",W:b.title},d3(a,b)]}]}]};c=new g.Q(c);e3(a,g.ee("iv-click-target",c.element),b,b.url);return c},f3=function(a){return a.customMessage?
b3("div","iv-card-message",a.customMessage):""},c3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",H:"iv-card-image",O:{style:c},J:d}},d3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(b3("li","",d))},a);
return{D:"ul",H:"iv-card-meta-info",J:c}},Tsa=function(a,b){return{D:"li",
H:Osa(a,b.index),J:[{D:"label",J:[{D:"input",H:"iv-card-poll-choice-input",O:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",H:"iv-card-poll-choice-text",J:[{D:"span",H:"iv-card-poll-choice-percent"},b3("span",void 0,b.desc)]}]},{D:"div",H:"iv-card-poll-result",J:[{D:"div",H:"iv-card-poll-result-bar"}]}]}},b3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Na(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.Rn(c);return{D:a,O:b,W:c}},Xsa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.ln&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.ln+");");c.dir=g.Rn(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",H:"iv-card-link-icon"}));return{D:"div",Y:b,O:c,J:d}},Usa=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.fe(Osa(a,e.index),b);e=e.count/c;null==a.Ee&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.Ee==d);f.getElementsByTagName("input")[0].checked=a.Ee==d;var k=Math.floor(100*e).toFixed(0),l=g.fe("iv-card-poll-choice-percent",f);g.Be(l,g.IM("$PERCENT%",{PERCENT:k}));f=g.fe("iv-card-poll-result-bar",f);g.wh(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.Ee);g.K(b,"iv-card-poll-expanded",
null!=a.Ee&&1<a.choices.length)},e3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Ob,c.Gc.click,5)},a)},Ysa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Zsa=function(a,b){return b?b:Ysa(a)?"current":"new"},g3=function(a,b){g.A.call(this);
var c=this;this.o=a;this.context=b;this.Pu=!1;this.la=new Map;this.oa=new Map;this.context.N.addEventListener(g.nC("annotations_module"),function(d){(d=c.la.get(d))&&d.apply(c)});
this.context.N.addEventListener("crx_annotations_module",function(d){(d=c.oa.get(d))&&d.apply(c)})},$sa=function(a,b,c,d,e){var f=Y2(b);
if(f){var k=Zsa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.N.pauseVideo();var m=this.context.videoData.lc||!1,n=g.rq(f||"");m&&n&&(n.v||n.list)?g.vT(this.context.N.app,n.v,c,n.list,!1,void 0):g.QM(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);$2(a.context.logger,d,l,e);Ysa(f)||(a=g.hs(),d=c.itct,a&&d&&g.Ds(a,g.$r(d)))}},ata=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},h3=function(a,b,c){return{Hx:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
aC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Tp:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},k3=function(a,b,c){g3.call(this,b,c);
var d=this;this.w=a;this.ha=this.Ia=this.C=this.Ha=!1;this.da=null;this.Z=new g.H(g.Ka,c.A.Ua?4E3:3E3);g.B(this,this.Z);this.za=new g.H(g.Ka);g.B(this,this.za);this.I=new a3(c,(0,g.x)(this.uk,this),(0,g.x)(this.zo,this));this.V=new g.Q({D:"div",H:"iv-drawer",O:{id:"iv-drawer"},J:[{D:"div",H:"iv-drawer-header",O:{"aria-role":"heading"},J:[{D:"span",H:"iv-drawer-header-text"},{D:"button",Y:["iv-drawer-close-button","ytp-button"],O:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",H:"iv-drawer-content"}]});
g.B(this,this.V);this.F=this.V.element;this.ua=new g.SL(this.V,330);g.B(this,this.ua);this.Ca=g.fe("iv-drawer-header-text",this.F);this.B=g.fe("iv-drawer-content",this.F);this.A=[];this.Aa=this.U=this.G=this.ga=this.u=null;this.aa=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ia&&i3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ia=d.C)&&j3(d)});
this.R=this.P=this.ba=null;this.L=0},bta=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){i3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){j3(a)});
var c=b.data.headerText;g.Be(a.Ca,c);a.U&&a.U.setAttribute("title",c);a.ba=g.$r(b.data.trackingParams);a.R=g.$r(b.data.closeTrackingParams);a.P=g.$r(b.data.iconTrackingParams)},cta=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.L;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.L,type:"simple",teaserText:g.U(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:l3(a,c,b,d),sponsored:!1,Gc:h3(d,e,d.command),de:d.trackingParams?g.$r(d.trackingParams):null,Xd:e.trackingParams?
g.$r(e.trackingParams):null,zd:f&&f.trackingParams?g.$r(f.trackingParams):null,imageUrl:m3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.U(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,ln:null,title:d.title?g.U(d.title):"",customMessage:d.callToAction?g.U(d.callToAction):"",url:d.command.urlEndpoint.url?X2({pause_on_navigation:!a.context.videoData.sa,target:"new",value:d.command.urlEndpoint.url}):null};n3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.L,type:"collaborator",teaserText:g.U(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:l3(a,c,b,d),sponsored:!1,Gc:h3(d,e,d.endpoint),de:d.trackingParams?g.$r(d.trackingParams):null,Xd:e.trackingParams?g.$r(e.trackingParams):null,zd:f&&f.trackingParams?
g.$r(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.U(d.customText):null,hB:m3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.U(d.channelName):"",metaInfo:[d.subscriberCountText?g.U(d.subscriberCountText):""],url:X2({pause_on_navigation:!a.context.videoData.sa,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};n3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.L,type:"playlist",teaserText:g.U(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:l3(a,c,b,d),sponsored:!1,Gc:h3(d,e,d.action),de:d.trackingParams?g.$r(d.trackingParams):null,Xd:e.trackingParams?g.$r(e.trackingParams):null,zd:f&&f.trackingParams?g.$r(f.trackingParams):
null,gj:m3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.U(d.customMessage):null,playlistVideoCount:g.U(d.playlistVideoCount),title:d.playlistTitle?g.U(d.playlistTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.videoCountText?g.U(d.videoCountText):""],url:X2({pause_on_navigation:!a.context.videoData.sa,target:"new",value:ata(d.action)})};n3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.L,type:"video",teaserText:g.U(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:l3(a,c,b,d),sponsored:!1,Gc:h3(d,e,d.action),de:d.trackingParams?g.$r(d.trackingParams):null,Xd:e.trackingParams?g.$r(e.trackingParams):null,zd:f&&f.trackingParams?g.$r(f.trackingParams):null,gj:m3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.U(d.lengthString):null,customMessage:d.customMessage?g.U(d.customMessage):null,title:d.videoTitle?g.U(d.videoTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.viewCountText?g.U(d.viewCountText):""],isLiveNow:!!d.badge,url:X2({pause_on_navigation:!a.context.videoData.sa,target:"new",value:ata(d.action)})};n3(a,c)}a.L++},m3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},l3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},eta=function(a,b){var c=dta(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.we(c.Rq),g.gb(a.A,c),a.on(),o3(a))},i3=function(a,b,c){if(!a.C){a.ua.show();
a.ga=new g.H(function(){g.I(a.context.N.getRootNode(),g.aS.IV_DRAWER_OPEN)},0);
a.ga.start();a.da=g.Jp(a.B,"mousewheel",(0,g.x)(a.GL,a));a.C=!0;var d=g.hs();d&&a.ba&&a.R&&B2(d,[a.ba,a.R]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.iy||(f.iy=!0,Rsa(a.context.logger,f.card.Gc.Hx,e));d&&B2(d,[f.card.de])});
A2(a.w);c&&(a.G=new g.H(function(){a.ya=a.U;a.Aa.focus()},330),a.G.start())}},j3=function(a){a.C&&(a.ua.hide(),g.Kp(a.da),a.da=null,g.Jn(a.context.N.getRootNode(),g.aS.IV_DRAWER_OPEN),a.C=!1,A2(a.w),a.G&&a.G.stop(),a.G=new g.H(function(){a.ya&&(a.ya.focus(),a.ya=null)},330),a.G.start())},fta=function(a){var b=g.fe("iv-drawer-close-button",a.F);
a.context.o.ia(b,"click",a.bE,a);a.context.o.ia(a.B,"touchend",function(){a.Z.start()});
a.context.o.ia(a.B,"scroll",a.rE,a);a.context.u.subscribe("onHideControls",function(){a.ha=!0});
a.context.u.subscribe("onShowControls",function(){a.ha=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.ha=g.Hn(a.w.getRootNode(),"ytp-autohide")});
a.aa.push(g.To("iv-button-shown",a.hG,a));a.aa.push(g.To("iv-button-hidden",a.gG,a));a.aa.push(g.To("iv-teaser-shown",a.kG,a));a.aa.push(g.To("iv-teaser-hidden",a.jG,a));a.aa.push(g.To("iv-teaser-clicked",a.iG,a))},n3=function(a,b){a.Ha||(g.In(a.o,[g.aS.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]),g.jL(a.w,a.F,5),fta(a),a.U=g.fe("ytp-cards-button",a.w.getRootNode()),a.Aa=g.fe("iv-drawer-close-button",a.F),a.Ha=!0);eta(a,b.id);var c=gta(a,b);if(c){var d={card:b,Rq:c.element,iy:!1},e=hta(a,d);g.ob(a.A,e,0,d);c.ca(a.B,e);a.on();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Ta(a.rO,d)):(c=1E3*a.context.N.getCurrentTime(),5E3>c&&c>b.startMs&&a.MB(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Ta(a.MB,d)),o3(a))}},gta=function(a,b){switch(b.type){case "simple":var c=
a.I;
var d=b.displayDomain?{D:"div",H:"iv-card-image-text",W:b.displayDomain}:"";var e=Xsa(b);d={D:"div",Y:["iv-card"],J:[{D:"a",H:"iv-click-target",O:{href:Y2(b.url)},J:[c3(b.imageUrl,d),{D:"div",H:"iv-card-content",J:[b3("h2",void 0,b.title),e]}]}]};d=new g.Q(d);e3(c,g.ee("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.I,d={D:"div",Y:["iv-card","iv-card-channel"],J:[{D:"a",Y:["iv-click-target"],O:{href:Y2(b.url),"data-ytid":b.channelId},J:[c3(b.hB),{D:"div",H:"iv-card-content",
J:[f3(b),{D:"h2",H:"iv-card-primary-link",W:b.title},d3(c,b)]}]}]},d=new g.Q(d),e3(c,g.ee("iv-click-target",d.element),b,b.url),d;case "episode":return Wsa(a.I,b,"iv-card-episode");case "movie":return Wsa(a.I,b,"iv-card-movie");case "playlist":return c=a.I,d={D:"div",Y:["iv-card","iv-card-playlist"],J:[{D:"a",H:"iv-click-target",O:{href:Y2(b.url)},J:[c3(b.gj,{D:"div",H:"iv-card-image-overlay",J:[{D:"span",H:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",H:"iv-card-content",J:[f3(b),
b3("h2","iv-card-primary-link",b.title),d3(c,b)]}]}]},d=new g.Q(d),e3(c,g.ee("iv-click-target",d.element),b,b.url),d;case "poll":return Vsa(a.I,b);case "productListing":c=a.I;var f=!g.db(b.offers);d=["iv-card"];e="";var k=Xsa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",H:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",H:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",J:k});d={D:"div",Y:d,O:{tabindex:"0"},J:[{D:"a",
Y:["iv-card-image","iv-click-target"],O:{style:"background-image: url("+b.imageUrl+");",href:Y2(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",H:"iv-card-content",J:[b.sponsored?{D:"div",H:"iv-card-sponsored",J:["Sponsored",{D:"div",H:"iv-ad-info-container",J:[{D:"div",H:"iv-ad-info",W:"{{adInfo}}"},{D:"div",H:"iv-ad-info-icon-container",J:[{D:"div",H:"iv-ad-info-icon"},{D:"div",H:"iv-ad-info-callout"}]}]}]}:"",{D:"a",H:"iv-click-target",O:{href:Y2(b.url)},J:[b3("h2",e,b.title),k]}]}]};d=new g.Q(d);
e=g.re("span");g.Be(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.ob(e,"adInfo");e3(c,g.ee("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.I,d=b.isLiveNow?{D:"span",Y:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",Y:["iv-card","iv-card-video"],J:[{D:"a",H:"iv-click-target",O:{href:Y2(b.url)},J:[c3(b.gj,b.videoDuration?{D:"span",H:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",H:"iv-card-content",
J:[f3(b),b3("h2","iv-card-primary-link",b.title),d3(c,b),d]}]}]},d=new g.Q(d),e3(c,g.ee("iv-click-target",d.element),b,b.url),d}return null},hta=function(a,b){if(0==a.A.length)return 0;
var c=g.ab(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},ita=function(a){return a.u?"productListing"==a.u.card.type:(0,g.vi)(a.A,function(b){return"productListing"==b.card.type})},o3=function(a){g.K(a.w.getRootNode(),"ytp-cards-shopping-active",ita(a))},jta=function(a,b){if(a.V.Ga()){var c=new G2([0,
a.B.scrollTop],[0,b.Rq.offsetTop],600,psa);a.context.w.ia(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ia(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.Jt(a.V,!0),a.B.scrollTop=b.Rq.offsetTop,g.Jt(a.V,!1)},p3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},dta=function(a,b){return g.$a(a.A,function(c){return c.card.id==b})},q3=function(a,b,c){g3.call(this,a,b);
this.annotation=c;this.isActive=!1},kta=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},r3=function(a,b,c){q3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},s3=function(a,b,c){q3.call(this,a,b,c);
this.P=this.C=this.L=!1;this.G=5E3;this.B=null;this.I=g.qe("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.H(function(){this.u.setAttribute("aria-hidden",!0);g.Qh(this.A,!1);g.Qh(this.w,!0)},700,this);
g.B(this,this.F)},lta=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=a.annotation.jc(),f=b.image_url;if(f){var k=g.qe("DIV",["iv-promo-img","iv-click-target"]);f=g.qe("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.qe("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.qe("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.uk(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.qe("A","iv-promo-txt"),g.ad(f,Y2(e)),a.u=f):a.u=g.qe("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.qe("P",null,g.qe("STRONG",null,b.text_line_1));var m=g.qe("P",null,g.qe("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.R(a.context.A.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.qe("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.qe("BUTTON",["iv-button","iv-promo-button"],g.qe("SPAN","iv-button-content",f));var p=g.qe("DIV","iv-promo-button-container");p.appendChild(f);e&&a.uk(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.I(a.u,"iv-click-target");e&&a.uk(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.qe("P",null,g.qe("SPAN",null,b.text_line_1)),
m=g.qe("P",null,g.qe("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.qe("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.I(a.u,"iv-click-target"),e&&a.uk(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.I.appendChild(a.u);p&&a.I.appendChild(p);c=g.qe("DIV","iv-promo-actions");a.w=g.qe("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ia(a.w,"click",g.Ta(a.Sr,5E3),a);c.appendChild(a.w);g.Qh(a.w,!1);
a.context.o.ia(a.o,"mouseover",a.qF,a);a.context.o.ia(a.o,"mouseout",a.pF,a);a.context.o.ia(a.o,"touchend",g.Ta(a.Sr,5E3),a);a.A=g.qe("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ia(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.iF:a.hF,a);c.appendChild(a.A);g.In(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.I);a.o.appendChild(c)},mta=function(a){a.C||a.P||a.B||(g.I(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},nta=function(a){a.F.stop();
a.C&&(g.Kn(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Qh(a.w,!1),g.Qh(a.A,!0))},ota=function(a,b){a.B||(a.B=g.Wf(function(){t3(this);
mta(this)},b,a))},t3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},u3=function(a){g.wL.call(this,a);
this.P=!1;this.I=0;this.F={};this.V=new Qsa(a);this.B=new g.O(this);g.B(this,this.B);this.C=this.w=null;this.B.K(this.player,"onVideoAreaChange",(0,g.x)(this.S,this,"onVideoAreaChange"));this.B.K(this.player,"onHideControls",(0,g.x)(this.S,this,"onHideControls"));this.B.K(this.player,"onShowControls",(0,g.x)(this.S,this,"onShowControls"));this.B.K(this.player,"resize",(0,g.x)(this.S,this,"resize"));this.B.K(this.player,"presentingplayerstatechange",(0,g.x)(this.S,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.eM,this);this.subscribe("resize",this.mp,this);this.player.M().I.subscribe("vast_info_card_add",this.TA,this);this.U=new g.O(this);g.B(this,this.U);this.R=g.qe("DIV","video-custom-annotations");this.u=new g.Q({D:"div",Y:["ytp-player-content","ytp-iv-player-content"]});g.B(this,this.u);g.jL(this.player,this.u.element,4);this.u.hide();this.A=new g.Q({D:"div",Y:["ytp-iv-video-content"]});g.B(this,this.A);g.te(this.A.element,g.qe("DIV","video-annotations",
this.R));this.G=this.o=null;this.L=[];pta(this)&&this.load();var b=g.re("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Je(this,function(){g.we(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},qta=function(){var a=g.qe("DIV",["annotation",
"annotation-type-custom"]);g.Qh(a,!1);return a},rta=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},pta=function(a){var b=a.player.M();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.CC||b.I.get(a.videoId)||g.LB(a)||g.MB(a)?!0:!1},sta=function(a,b,c){a.P=!0;
a.C=g.Jq(b,c)},tta=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Qa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(tta(a,e))}return c},uta=function(a,b,c){return!(a.loaded&&a.I==b&&a.player.getVideoData().videoId==
c)},xta=function(a){var b=a.player.getVideoData();
if(b.be){var c=a.player.M().I.get(b.videoId);if(c){var d={format:"XML",Zd:{},method:"POST",withCredentials:!0};d.Fc=(0,g.x)(function(e,f,k){uta(this,e,f)||(e=g.Dq(k)&&k.responseXML?k.responseXML:null)&&v3(this,e)},a,a.I,b.videoId);
g.$p()&&(d.Fc=vta(a,d.Fc));d.rb={ic_only:"1"};wta(d,c);a.P=!0;g.Jq(b.be,d)}}},wta=function(a,b){a.method="POST";
a.rb=a.rb||{};b.tn&&(a.rb.ic_coll=b.tn);b.un&&(a.rb.ic_xml=b.un);b.Km&&(a.rb.ic_track=b.Km)},yta=function(a){var b=new g.Q({D:"div"});
g.Qh(b.element,!1);var c=new k3(a.player,b.element,w3(a));g.B(c,b);b.ca(a.u.element);c.zm();return c},w3=function(a){if(!a.G){var b=new J2(a);
g.B(a,b);var c=new g.C1(a);g.B(a,c);a.G=new Ssa(b,c,a.player.M(),a.player.getVideoData(),a.V,a.player,a.Lh)}return a.G},v3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.hs();if(e){var f=g.fs();f&&g.xs(g.Co("use_default_events_client")?void 0:g.Vq,e,f,[g.$r(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=tta(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=W2(k.type,zta),t=W2(k.style,Ata),u=V2(k.data),z=0!=u.length?JSON.parse(u):{},C=Gsa(k.action);f=n&&p?new Z2(n,p,t,C,z):null}else f=null}catch(ha){}if(f){a:{switch(f.type){case "branding":case "promotion":k=
!0;break a}k=!1}if(k){k=a;m=f;var D=qta(),E=null;switch(m.type){case "branding":if(k.player.M().Aa)break;k.u.element.appendChild(D);E=new r3(D,w3(k),m);break;case "promotion":g.jL(k.player,D,4),E=new s3(D,w3(k),m)}E&&E.zm();if(k=E)g.B(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=yta(a),g.B(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Hx:k.impression,click:k.click,close:k.close,aC:k.teaser_impression,Tp:k.teaser_click},m=
f.data.tracking_params||{},D=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,de:m.card?g.$r(m.card):null,Xd:m.teaser?g.$r(m.teaser):null,zd:m.icon?g.$r(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,hB:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};n3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,de:m.card?g.$r(m.card):null,Xd:m.teaser?g.$r(m.teaser):null,
zd:m.icon?g.$r(m.icon):null,gj:f.data.image_url,Uv:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,YF:!!f.data.is_paygated,aP:!!f.data.user_has_entitlement,url:X2({target:f.data.target||"new",value:f.data.url})};n3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||
{},sponsored:f.data.sponsored||!1,Gc:k,de:m.card?g.$r(m.card):null,Xd:m.teaser?g.$r(m.teaser):null,zd:m.icon?g.$r(m.icon):null,gj:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};n3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,
teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,de:m.card?g.$r(m.card):null,Xd:m.teaser?g.$r(m.teaser):null,zd:m.icon?g.$r(m.icon):null,title:f.data.title,choices:f.data.choices,Ee:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,bj:f.data.signin_url?X2({target:"current",value:f.data.signin_url}):null,lP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};n3(c,f);break;case "productListing":f.data.signin_url&&
(D=X2({target:"current",value:f.data.signin_url}));E=[];for(var F=f.data.offers||[],J=0;J<F.length;J++)E.push(new Psa(g.id(F[J].merchant),g.id(F[J].price)));f={rT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,de:m.card?g.$r(m.card):null,Xd:m.teaser?g.$r(m.teaser):null,zd:m.icon?g.$r(m.icon):null,
imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,ln:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),bj:D,LT:f.data.signin_title?f.data.signin_title:null,KT:f.data.signin_message?f.data.signin_message:null,offers:E};n3(c,f);break;case "simple":f=
{id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,de:m.card?g.$r(m.card):null,Xd:m.teaser?g.$r(m.teaser):null,zd:m.icon?g.$r(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,ln:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};n3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,de:m.card?g.$r(m.card):null,Xd:m.teaser?
g.$r(m.teaser):null,zd:m.icon?g.$r(m.icon):null,gj:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},n3(c,f)}}else bta(a.o,f);c=!0}}}c&&(A2(a.player),a.mp())},Bta=function(a,b){var c=!1;
a.o||(a.o=yta(a),g.B(a,a.o));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())cta(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.U(b.headerText):"",g.Be(c.Ca,d),c.U&&c.U.setAttribute("title",d),c.ba=b.trackingParams?g.$r(b.trackingParams):null,c.R=b.closeButton.infoCardIconRenderer.trackingParams?g.$r(b.closeButton.infoCardIconRenderer.trackingParams):null,c.P=b.icon.infoCardIconRenderer.trackingParams?g.$r(b.icon.infoCardIconRenderer.trackingParams):null,A2(a.player),a.mp())},
Cta=function(a,b,c,d,e){if(!a.player.M().Aa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Ksa("openUrl","click",new Isa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.U(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.U(b.subscriberCountText))):(b.subscriberCountText&&(e=g.U(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.U(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.U(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.U(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Z2(c,"branding","branding",f,d);d=qta();a.u.element.appendChild(d);f=new r3(d,w3(a),f);f.zm();g.B(f,f);a.F[c]=f}},vta=function(a,b){return(0,g.x)(function(){if(!this.ea()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ta.apply(window,c);this.L.push(g.Yp(b))}},a)},D2={},E2=null;g.Va(G2,g.Ln);g.h=G2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(this.ab())return!1;F2(this);this.startTime=a=(0,g.G)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.kp();this.se("play");-1==this.o&&this.se("resume");this.o=1;var b=g.Sa(this);b in D2||(D2[b]=this);rsa();ssa(this,a);return!0};
g.h.stop=function(a){F2(this);this.o=0;a&&(this.progress=1);tsa(this,this.progress);this.se("stop");this.km()};
g.h.pause=function(){this.ab()&&(F2(this),this.o=-1,this.se("pause"))};
g.h.X=function(){0==this.o||this.stop(!1);this.se("destroy");G2.Fb.X.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Ht=function(){this.se("animate")};
g.h.se=function(a){this.dispatchEvent(new usa(a,this))};
g.Va(usa,g.Me);g.Va(H2,G2);H2.prototype.A=g.Ka;H2.prototype.Ht=function(){this.A();H2.Fb.Ht.call(this)};
H2.prototype.km=function(){this.A();H2.Fb.km.call(this)};
H2.prototype.kp=function(){this.A();H2.Fb.kp.call(this)};
g.Va(I2,H2);I2.prototype.A=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(J2,g.A);J2.prototype.ia=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Jp(a,b,c);this.o.push(a);return a};
J2.prototype.Ds=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Tp(a,b,c);this.o.push(a);return a};
J2.prototype.Ya=function(a){g.Kp(a);g.gb(this.o,a)};
J2.prototype.X=function(){g.Kp(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.r(N2,g.wL);g.h=N2.prototype;g.h.load=function(){g.wL.prototype.load.call(this);if(!O2(this)){var a=g.KB(this.player.getVideoData());if(a)a=M2(a,xsa(this)),P2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",Fc:(0,g.x)(this.QK,this,a),Zd:{v:a},withCredentials:!0};this.P&&(a.Zd.ptype="embedded");var c=this.player.getVideoData().Gn;c&&(a.rb={ad_tracking:c});if(b=g.JB(b))if(b=g.yc(b),b=g.wc(b))this.A=g.Jq(b,a)}}};
g.h.unload=function(){P2(this,null);this.A&&(this.A.abort(),this.A=null);g.wL.prototype.unload.call(this)};
g.h.Oc=function(a,b){if(!O2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=M2(b,"new");P2(this,c);return!0}return null};
g.h.getOptions=function(){return O2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.QK=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=M2(c,xsa(this)))}P2(this,c)};
g.h.Dy=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Dta.length;f++){var k=Math.abs(b.width-Dta[f]);if(-1==e||d>=k)e=f,d=k}d=Eta[e];this.w&&g.wh(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Oh(e.element,Math.round(k.width*a.width),f);g.Eh(e.element,m,n);g.Kn(e.element,Fta);m=k.left+k.width/2;k=k.top+l/2;g.I(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Kn(e.element,Eta);g.I(e.element,d);(e=g.de(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.wh(e,"height",f+"px")}}}}};
g.h.MG=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())T2(this,this.u.impressionUrls),(a=g.hs())&&this.u.visualElement&&g.ys(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");T2(this,c.impressionUrls);(b=g.hs())&&g.ys(b,c.visualElement);this.player.M().w&&this.player.na("endscreenelementshown",a)}};
g.h.NG=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.Jn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Jn(b,"ytp-ce-shown");this.player.M().w&&this.player.na("endscreenelementhidden",a)}};
g.h.EN=function(a){var b=this;a.target===window&&(new g.H(function(){for(var c in b.o)g.Kn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.hA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Hn(c,"ytp-ce-element");){g.Hn(c,"subscribe-label")&&U2(this,a);if(g.Hn(c,"ytp-ce-channel-subscribe"))return;c=g.ze(c)}if(!c||g.Hn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Mt(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.HO?(U2(this,a),this.LB(),this.player.pauseVideo(),c=g.yc(R2(this,a.targetUrl)),c=g.wc(c),g.QM(c,void 0,a.Ob)):(c=this.player.getVideoData().lc,
c=(0,g.x)(this.zO,this,c,R2(this,a.targetUrl),a.Ob),c=(0,g.x)(this.LB,this,c),U2(this,a,c))}}};
g.h.zO=function(a,b,c){var d=g.rq(b);a&&d&&(d.v||d.list)?g.vT(this.player.app,d.v,c,d.list,!1,void 0):g.PM(b,c)};
g.h.Ns=function(a,b){g.Hn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.M().o?(new g.H(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),T2(this,b.NF),S2(this,b.id,!0))};
g.h.Mt=function(a,b){g.Jn(a.element,"ytp-ce-element-hover");g.Jn(a.element,"ytp-ce-force-expand");S2(this,b.id,!1)};
g.h.LB=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Dta=[346,426,470,506,570,640,853,1280,1920],Eta="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Fta=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Jsa={qQ:"current",OR:"new"};var Lsa={CLOSE:"close",RR:"openUrl",yD:"subscribe"},Msa={kQ:"click",CLOSE:"close",eR:"hidden",wS:"rollOut",xS:"rollOver",AS:"shown"};Z2.prototype.jc=function(){var a=Nsa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var Ata={NP:"anchored",SC:"branding",CHANNEL:"channel",pQ:"cta",gR:"highlightText",xR:"label",PLAYLIST:"playlist",jS:"popup",ES:"speech",yD:"subscribe",OS:"title",VIDEO:"video",cT:"website"},zta={SC:"branding",bQ:"card",xQ:"drawer",fR:"highlight",ER:"marker",oS:"promotion",TEXT:"text",eT:"widget"};a3.prototype.u=function(a,b){var c=g.Ge(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
a3.prototype.A=function(a,b){var c=g.Ge(b.target,null,"iv-card-poll",void 0);if(c)if(a.bj)g.fe("iv-card-sign-in-button",c).click();else{var d=parseInt(nsa(b.target),10);if(null==a.Ee)a.choices[d].count++,a.Ee=d;else if(a.Ee!=d){var e=a.choices[a.Ee];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.Ee=d}else e=a.choices[a.Ee],e.count=Math.max(e.count-1,0),a.Ee=null;Usa(a,c);g.Nq(this.o.videoData.be,{Zd:{action_poll_vote:1},rb:{poll_id:a.id,index:d,session_token:a.lP}});$2(this.o.logger,a.Gc.click,
void 0,5);(c=g.hs())&&a.de&&g.Ds(c,a.de)}};g.r(g3,g.A);g.h=g3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.kC(a,b,{id:c});a.namespace="annotations_module";d&&this.la.set(a,d);e&&this.oa.set(a,e);g.fL(this.context.N,[a])};
g.h.zm=function(){this.context.u.subscribe("resize",this.on,this)};
g.h.uk=function(a,b,c,d,e,f){this.context.o.ia(a,"click",g.Ta(this.zo,b,c,d,e||[],f||0),this);this.context.o.ia(a,"touchstart",g.Ta(function(){this.Pu=!1}),this);
this.context.o.ia(a,"touchmove",g.Ta(function(){this.Pu=!0}),this)};
g.h.zo=function(a,b,c,d,e,f){if(this.Pu)return!1;f&&(f.stopPropagation(),f.preventDefault());$sa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.we(this.o)};
g.h.on=function(){};
g.h.X=function(){this.la.clear();this.oa.clear();g.A.prototype.X.call(this)};g.r(k3,g3);g.h=k3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.w.getRootNode())?(a=g.Ph(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.on=function(){var a=this.isAvailable();g.Qh(this.o,a);g.K(this.context.N.getRootNode(),g.aS.IV_DRAWER_ENABLED,a);A2(this.w)};
g.h.destroy=function(){var a=g.YK(g.LK(this.w));a&&a.Js(!1,void 0);try{this.w.getRootNode().removeChild(this.F)}catch(b){}g.Uo(this.aa);g.Kp(this.da);this.ga&&this.ga.dispose();this.G&&this.G.dispose();g3.prototype.destroy.call(this)};
g.h.GL=function(a){this.Z.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.MB=function(a){if(!g.Hn(this.w.getRootNode(),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.hs(),c=this.u?this.u.card.zd:this.P;b&&c&&C2(b,[c]);this.u=a;o3(this)}if(b="none"!=this.o.style.display)2==this.context.N.getPresentingPlayerType()?b=1==this.context.N.getAdState():(b=this.context.N.getPlayerState(),c=0==b&&0===this.context.N.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.YK(g.LK(this.w)))&&c.Js(!0,
b));this.za.isActive()||((!this.C||!this.Z.isActive()&&this.ha)&&jta(this,a),this.za.start(910+a.card.teaserDurationMs))}};
g.h.rO=function(a){this.C||(this.u=a,o3(this),jta(this,a),i3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.bE=function(){if(this.C){$2(this.context.logger,p3(this).Gc.close);var a=g.hs();a&&this.R&&g.Ds(a,this.R);j3(this)}};
g.h.rE=function(){g.K(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.hG=function(){var a=g.hs(),b=p3(this);b=b?b.zd:this.P;a&&b&&B2(a,[b])};
g.h.gG=function(){var a=g.hs(),b=p3(this);b=b?b.zd:this.P;a&&b&&C2(a,[b])};
g.h.kG=function(){var a=p3(this);$2(this.context.logger,a.Gc.aC);var b=g.hs();b&&a&&B2(b,[a.Xd,a.zd])};
g.h.jG=function(){var a=g.hs(),b=p3(this);a&&b&&C2(a,[b.Xd])};
g.h.iG=function(a){var b=p3(this),c=g.hs();this.u?a?(a=this.context.logger,$2(a,b.Gc.Tp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Xd&&g.Ds(c,b.Xd)):(a=this.context.logger,$2(a,b.Gc.Tp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.zd&&g.Ds(c,b.zd)):(a=this.context.logger,$2(a,b.Gc.Tp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.P&&g.Ds(c,this.P))};g.r(q3,g3);q3.prototype.zm=function(){g3.prototype.zm.call(this);kta(this)};
q3.prototype.show=function(){g3.prototype.show.call(this);var a=g.hs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&B2(a,[g.$r(b.itct)])};
q3.prototype.hide=function(){g3.prototype.hide.call(this);var a=g.hs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&C2(a,[g.$r(b.itct)])};g.r(r3,q3);g.h=r3.prototype;g.h.AO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Ph(a);this.u||(g.Nh(a,e.width),g.Nh(b,e.width));g.wh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.wh(c,"right","1px");this.B=!0;g.Qh(a,!0);this.C=new g.H(function(){g.I(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.MF=function(a,b){g.Jn(this.o,"iv-branding-active");this.F=new g.H((0,g.x)(function(){g.Qh(a,!1);this.u||g.Nh(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){q3.prototype.show.call(this);if(!this.G){g.I(this.o,"iv-branding");var a=this.annotation.data;this.w=g.qe("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Qh(this.w,!1);var b=g.qe("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=this.annotation.jc())&&this.uk(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.qe("DIV","iv-branding-context-name");
g.Be(c,a.channel_name);var d=g.qe("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.LP(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.N),this.u.ca(d);b=g.qe("DIV","iv-branding-context-subscribe-caret");c=g.qe("DIV","branding-context-container-inner",b,c,d);g.Qh(c,!1);d=g.qe("DIV","branding-context-container-outer",c);g.wh(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.H(g.Ta(this.MF,c,d),500,this);g.B(this,this.A);this.context.o.ia(this.o,"mouseover",(0,g.x)(this.AO,this,c,d,b,a.image_height));this.context.o.ia(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Qh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.Ih(a);c=g.Ph(a);b=(new g.th(b.x,b.y,c.width,c.height)).width;g.Eh(a,b);e=new I2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,osa);g.B(this,e);this.context.w.ia(e,
"begin",g.Ta(g.Qh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(q3.prototype.hide.call(this),g.Qh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);q3.prototype.destroy.call(this)};g.r(s3,q3);g.h=s3.prototype;g.h.show=function(){this.isActive||(q3.prototype.show.call(this),this.L||(lta(this),this.L=!0),g.Qh(this.o,!0),g.Wf(function(){g.Jn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,t3(this),nta(this),ota(this,this.G))};
g.h.hide=function(){this.isActive&&(g.I(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.zo=function(a,b,c,d,e,f){return this.C?!1:q3.prototype.zo.call(this,a,b,c,d,e,f)};
g.h.Sr=function(a,b){b.stopPropagation();nta(this);ota(this,a);this.u.focus()};
g.h.qF=function(a){this.P=!0;this.Sr(500,a)};
g.h.pF=function(){this.P=!1;mta(this)};
g.h.hF=function(a){a.stopPropagation();this.hide()};
g.h.iF=function(a){a.stopPropagation();t3(this);this.C=!0;g.I(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();q3.prototype.destroy.call(this)};g.r(u3,g.wL);g.h=u3.prototype;g.h.Oc=function(a,b){if(!rta(this.player.M().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.B1(b);c&&v3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(eta(this.o,b),A2(this.player)),!0}return null};
g.h.getOptions=function(){return rta(this.player.M().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.mp=function(){if(this.A){var a=g.RK(this.player).getVideoContentRect(!0);g.Oh(this.A.element,a.width,a.height);g.Eh(this.A.element,a.left,a.top)}if(this.o){var b=g.aL(this.player);a=this.o;b=b.width;g.K(a.F,"iv-drawer-small",426>=b);g.K(a.F,"iv-drawer-big",1280<=b)}};
g.h.eM=function(a){this.Sf(a.state);g.V(a.state,2)&&(this.Pl()&&this.ry()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Js(!1))};
g.h.load=function(){g.wL.prototype.load.call(this);this.Sf(g.QK(this.player));this.I++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.SK,this,b,this.I),d=(0,g.x)(function(){this.C=null},this);
g.$p()&&(c=vta(this,c));c={format:"XML",Fc:c,onError:d,Zd:{}};a.isPharma&&(c.Zd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.M().I.get(b))&&wta(c,b);b=b&&(b.un||b.tn);if(!a.fn||b)a.be?sta(this,a.be,c):(this.w=(0,g.x)(this.KG,this,c),this.player.addEventListener("videodatachange",this.w));g.jL(this.player,this.A.element,4);this.mp();(b=g.LB(a))&&Bta(this,b);(b=g.MB(a))&&b.featuredChannel&&Cta(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.Sf=function(a){a=!a.isCued()&&!g.V(a,1024);g.Jt(this.u,a);g.Jt(this.A,a)};
g.h.KG=function(a){var b=this.player.getVideoData();b.be&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),sta(this,b.be,a))};
g.h.unload=function(){g.sQ(this.player.app,"annotations_module",void 0);g.Ab(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,A2(this.player));this.P=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.wL.prototype.unload.call(this);g.Gt(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.SK=function(a,b,c){this.C=null;!uta(this,b,a)&&(a=g.Dq(c)&&c.responseXML?c.responseXML:null)&&(v3(this,a),g.I(this.player.getRootNode(),"iv-module-loaded"))};
g.h.TA=function(a){a==this.player.getVideoData().videoId&&(this.loaded?xta(this):this.load())};
g.h.Pl=function(){return!!this.o&&this.o.isAvailable()};
g.h.ry=function(){this.Pl();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Pl();this.o&&(a?c?i3(this.o,c,b):i3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):j3(this.o))};
g.h.Js=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.X=function(){this.player.M().I.unsubscribe("vast_info_card_add",this.TA,this);g.Jn(this.player.getRootNode(),g.aS.IV_DRAWER_OPEN);for(var a=this.L,b=0,c=a.length;b<c;b++)g.aq(a[b]);this.L.length=0;g.wL.prototype.X.call(this)};g.LL.annotations_module=u3;g.LL.creatorendscreen=N2;})(_yt_player);
